name: SonarQube Analysis

on:
  push:
    branches: [ main, dev, production, master ]
  pull_request:
    branches: [ production, dev, test, master ]
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup backend test structure
        run: |
          mkdir -p ./tests
          touch ./tests/__init__.py
          mv ./test_app.py ./tests/

      - name: Create sonar properties
        run: |
          cat > sonar-project.properties << 'EOL'
          sonar.projectName=LMS System
          sonar.sources=backend-flask
          sonar.tests=./tests
          sonar.exclusions=**/node_modules/**,**/*.test.js,**/*.test.tsx,**/tests/**,**/coverage/**
          sonar.test.inclusions=**/*.test.js,**/*.test.tsx,**/test_*.py
          sonar.python.coverage.reportPaths=./coverage.xml
          sonar.sourceEncoding=UTF-8
          sonar.python.version=3.10
          EOL

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run backend tests with coverage
        run: |
          python -m pytest tests/ --cov=. --cov-report=xml --cov-report=term-missing

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
